version: 2.1

orbs:
  maven: circleci/maven@0.0.9
  #allure: ayte/allure@0.1.2

executors:
  selenoid:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: selenoid/chrome:latest
        environment:
          PORT: 4444
    working_directory: ~/repo/testng

jobs:
  check_selenoid:
    docker:
      - image: selenoid/chrome:latest
        environment:
          PORT: 4444
    steps:
      - run: curl http://127.0.0.1:4444/status
      - run: curl -XPOST http://127.0.0.1:4444/session -d '{"desiredCapabilities":{"browserName":"chrome"}}'
      - run: curl http://127.0.0.1:4444/status

workflows:
  version: 2
  autotest_and_report:
    jobs:
      - check_selenoid
      - maven/test:
          executor: selenoid
          #test_results_path: target/surefire-reports
          settings_file: ''
          #command: 'with_cache process_test_results'

      #- allure/allure