version: 2

workflows:
  version: 2
  autotest_and_report:
    jobs:
    - maven_test

jobs:
  maven_test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers
        environment:
          MAVEN_OPTS: -Xmx1024m
        entrypoint: ["/bin/sh"]
        command: [Xvfb :99 -screen 0 1920x1080x24 &\nexec "$@"\n]

    working_directory: ~/project/testng
    steps:
    - checkout:
        path: ~/project
    - run:
        name: Browsers versions
        command: |
          chromedriver --version
          google-chrome --version
          geckodriver --version
          firefox --version
    - restore_cache:
        keys:
          - ebaymag-{{ checksum "pom.xml" }}
          - ebaymag-
    - run:
        name: Resolve Maven dependencies
        command: mvn dependency:go-offline compile compiler:testCompile
        #when: always
    - run:
        #halt_build_on_fail: true
        name: Autotests
        command: mvn test
        #when: always
    - run:
        name: Allure Report
        command: mvn allure:report
        when: always
    - save_cache:
        paths:
          - ~/.m2
          - .allure
        key: ebaymag-{{ checksum "pom.xml" }}
        when: always
    - store_test_results:
        path: target/surefire-reports/junitreports
    - store_artifacts:
        path: target/surefire-reports
        destination: report/testng-results
    - store_artifacts:
        path: target/allure-results
        destination: report/allure-results
    - store_artifacts:
        path: target/site/allure-maven-plugin
        destination: Allure