version: 2

executors:
  selenoid:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: selenoid/chrome:latest
        environment:
          PORT: 4444
    #working_directory: ~/repo/testng

workflows:
  version: 2
  autotest_and_report:
    jobs:
    - maven_test

jobs:
  maven_test:
    executor: selenoid
    working_directory: testng
    steps:
    - checkout
    - restore_cache:
        keys:
          - ebaymag-{{ checksum "pom.xml" }}
          - ebaymag-
    - run:
        name: Resolve Maven dependencies
        command: mvn dependency:go-offline compile compiler:testCompile
    - run:
        halt_build_on_fail: false
        name: Autotests
        command: mvn test -Dselenoid.url=http://127.0.0.1:4444
    - run:
        name: Allure Report
        command: mvn allure:report
        when: always
    - save_cache:
        paths:
          - ~/.m2
          - .allure
        key: ebaymag-{{ checksum "pom.xml" }}
        when: always
    - store_test_results:
        path: target/surefire-reports/junitreports
    - store_artifacts:
        path: target/surefire-reports
        destination: report
    - store_artifacts:
        path: target/allure-results
        destination: allure-results
    - store_artifacts:
        path: target/site/allure-maven-plugin
        destination: Allure