version: 2

workflows:
  version: 2
  autotest_and_report:
    jobs:
    - maven_test

jobs:
  maven_test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers
        environment:
          MAVEN_OPTS: -Xmx1024m
      #- image: selenoid/chrome:latest
      #  environment:
      #    PORT: 4444
    working_directory: ~/project/testng
    steps:
    - checkout:
        path: ~/project
    - run:
        name: Browsers versions
        command: |
          chromedriver --version
          google-chrome --version
          geckodriver --version
          firefox --version
    - run:
        name: Selenoid install
        command: curl -s https://aerokube.com/cm/bash | bash
    - run:
        name: Selenoid
        command: |
          ./cm selenoid start --browsers-json browsers.json --use-drivers
          sleep 100
        background: true
    #- run: sleep 5
    - restore_cache:
        keys:
          - ebaymag-{{ checksum "pom.xml" }}
          - ebaymag-
    - run:
        name: Resolve Maven dependencies
        command: mvn dependency:go-offline compile compiler:testCompile
        #when: always
    - run:
        name: Check selenoid
        command: curl http://127.0.0.1:4444/status
        when: always
    - run:
        name: Check selenoid 2
        command: curl -X POST http://127.0.0.1:4444/wd/hub/session -d '{"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"binary":"/usr/local/bin/firefox"}}}'
        when: always
    - run:
        name: Check selenoid 1
        command: curl -X POST http://127.0.0.1:4444/wd/hub/session -d '{"desiredCapabilities":{"browserName":"chrome","binary":"/opt/google/chrome/google-chrome --enable-logging=stderr --v=1"}}'
        when: always
    - run:
        name: Check selenoid 3
        command: curl http://127.0.0.1:4444/status
        when: always
    - run:
        #halt_build_on_fail: true
        name: Autotests
        command: mvn test -Dselenoid.url=http://127.0.0.1:4444/wd/hub
        #when: always
    - run:
        name: Allure Report
        command: mvn allure:report
        when: always
    - save_cache:
        paths:
          - ~/.m2
          - .allure
        key: ebaymag-{{ checksum "pom.xml" }}
        when: always
    - store_test_results:
        path: target/surefire-reports/junitreports
    - store_artifacts:
        path: target/surefire-reports
        destination: report/testng-results
    - store_artifacts:
        path: target/allure-results
        destination: report/allure-results
    - store_artifacts:
        path: target/site/allure-maven-plugin
        destination: Allure
    - store_artifacts:
        path: ~/.aerokube/selenoid
        destination: Selenoid