version: 2.0

jobs:
  maven_test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers
        environment:
          MAVEN_OPTS: -Xmx1024m
    description: "Run maven autotests and generate Allure report"
    #parameters:
    #  staging:
    #    type: string
    #    default: "alpha"
    #  suite:
    #    type: string
    #    default: "all" # browsers smoke
    working_directory: ~/project/testng
    steps:
    - checkout:
        path: ~/project
    - run:
        name: Browsers versions
        command: |
          chromedriver --version
          google-chrome --version
          geckodriver --version
          firefox --version
    - restore_cache:
        keys:
          - ebaymag-{{ checksum "pom.xml" }}
          - ebaymag-

    - run:
        name: Resolve Maven dependencies
        command: mvn dependency:go-offline compile compiler:testCompile
    - run:
        name: Autotests
        command: mvn test -Dstaging=$STAGING -Dsurefire.suiteXmlFiles=$SUITE.xml
    - run:
        name: Generate environment properties
        command: echo "BUILD_NUM=$CIRCLE_BUILD_NUM \nstaging=$STAGING \nsuite=$SUITE" >> target/allure-results/environment.properties
        when: always

    - run:
        name: Make history dir for allure
        command: mkdir target/allure-results/history
        when: always
    - run:
        name: Get previous artifact links
        command: curl https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts?circle-token=$artifacts | grep -o 'https:\/\/[^"]*history\/history.*\.json' > artifacts.txt
        when: always
    - run:
        name: Download history artfacts
        command: <artifacts.txt xargs -P4 -I % wget %?circle-token=$artifacts
        when: always
    - run:
        name: Rename and copy history artifacts to allure-result
        command: |
          mv history.json?circle-token=$artifacts history.json && mv history-trend.json?circle-token=$artifacts history-trend.json
          cp history.json target/allure-results/history/ && cp history-trend.json target/allure-results/history/
        when: always

    - run:
        name: Allure Report
        command: mvn allure:report
        when: always

    - save_cache:
        paths:
          - ~/.m2
          - .allure
        key: ebaymag-{{ checksum "pom.xml" }}
        when: always
    - store_test_results:
        path: target/surefire-reports/junitreports
    - store_artifacts:
        path: target/surefire-reports
        destination: report/testng-results
    - store_artifacts:
        path: target/allure-results
        #destination: report/allure-results
    - store_artifacts:
        path: target/site/allure-maven-plugin
        destination: Allure

workflows:
  version: 2
  autotests_and_report:
    jobs:
      - maven_test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
    jobs:
      - maven_test