name: Autotests on Selenoid

on:
  push:
    branches-ignore:
    - '!master' # Push events to branches matching allure-report
    #paths-ignore:
    #- 'docs/**'

jobs:
  autotests:
    name: Run autotests on selenoid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      #- name: initialize the X11 DISPLAY variable
      #  run: export DISPLAY=:99

      - name: chrome version
        run: |
          google-chrome --version
          which google-chrome

      - name: Install dependencies
        run: mvn -f testng/pom.xml dependency:go-offline compile compiler:testCompile

      - name: Run Test
      #  env:
      #    DISPLAY: :99
        run: mvn -f testng/pom.xml test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Keep Allure history
        run: cp -r $(pwd)/gh-pages/history/. $(pwd)/testng/target/allure-results/history

      - name: Generate Allure report
        run: mvn -f testng/pom.xml allure:report
        continue-on-error: true

      - uses: actions/upload-artifact@master
        with:
          name: allure-report
          path: testng/target/site/allure-maven-plugin

      - name: Deploy report to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.1.0
        #if: always()
        with:
          #ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: testng/target/site/allure-maven-plugin # The folder the action should deploy.
          #TARGET_FOLDER: docs
          CLEAN: true